# LiveKit Agent Configuration for AIME Voice Agent
apiVersion: livekit.io/v1
kind: Agent
metadata:
  name: aime-voice-agent
  description: AI-powered voice agent for GoHighLevel CRM integration
spec:
  # Runtime configuration
  runtime: python
  pythonVersion: "3.11"

  # Entry point
  entryPoint: voice_agent.py

  # Environment variables
  env:
    # LiveKit connection (automatically provided by LiveKit Cloud)
    LIVEKIT_URL: "wss://ezwaiaime-y90r6gwr.livekit.cloud"
    LIVEKIT_API_KEY: "APIy6Cd2R86Kwzx"
    LIVEKIT_API_SECRET: "Gtd7W5eaQseNKUNTYS6LDcUeGARbOdMgylnCIHazByfD"

    # OpenClaw Bridge (use ngrok for development)
    OPENCLAW_BASE_URL: "http://localhost:3000"

    # Speech-to-Text (Deepgram)
    DEEPGRAM_API_KEY: "${DEEPGRAM_API_KEY}"

    # LLM Provider (OpenAI for TTS/initial LLM)
    OPENAI_API_KEY: "${OPENAI_API_KEY}"

    # LLM Provider (Anthropic for advanced reasoning)
    ANTHROPIC_API_KEY: "${ANTHROPIC_API_KEY}"

    # Logging
    LOG_LEVEL: "INFO"

  # Resource limits
  resources:
    requests:
      cpu: "1000m"
      memory: "1Gi"
    limits:
      cpu: "2000m"
      memory: "2Gi"

  # Scaling configuration
  scaling:
    minReplicas: 1
    maxReplicas: 10
    targetConcurrency: 5

  # Health checks
  healthCheck:
    enabled: true
    path: /health
    interval: 30s
